FROM node:12

RUN apt update && apt install -y zip \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/app && chown -R node:node /usr/src/app

WORKDIR /usr/src/app

COPY --chown=node:node . .

USER node

RUN npm install \
    && npm install jpegtran-bin \
    && npm rebuild jpegtran-bin \
    && npm run build

RUN zip -r dist.zip dist
