FROM node:10

RUN useradd -ms /bin/bash appuser \
    && mkdir -p /app \
    && chown -R appuser:appuser /app

WORKDIR /app

COPY --chown=appuser:appuser package.json yarn.lock ./

USER appuser

RUN yarn install --frozen-lockfile

COPY --chown=appuser:appuser . .

RUN npm run build-dev --prod --build-optimizer
RUN npm run compress:brotli

WORKDIR /app/dist
RUN npm install --production
EXPOSE 3024

CMD [ "npm", "run", "serve:prod" ]

